# Generated by Django 5.1.4 on 2024-12-12 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccount_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('otp', models.CharField(max_length=6, verbose_name='otp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_email_verified',
        ),
    ]
